// <auto-generated />
using MSSA_Covid.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace MSSA_Covid.Migrations
{
    [DbContext(typeof(DefaultDBContext))]
    [Migration("20210222040541_InitialCreate")]
    partial class InitialCreate
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.3")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("MSSA_Covid.Data.Models.Location", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("City")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("County")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ImageBlobUrl")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ImageName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("State")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Url")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Locations");

                    b.HasData(
                        new
                        {
                            Id = -10,
                            City = "Pensacola",
                            County = "Escambia",
                            State = "Florida"
                        },
                        new
                        {
                            Id = -1,
                            City = "Fort Walton Beach",
                            County = "Okaloosa",
                            State = "Florida"
                        },
                        new
                        {
                            Id = -2,
                            City = "Crestview",
                            County = "Okaloosa",
                            State = "Florida"
                        },
                        new
                        {
                            Id = -4,
                            City = "Niceville",
                            County = "Okaloosa",
                            State = "Florida"
                        },
                        new
                        {
                            Id = -5,
                            City = "Destin",
                            County = "Okaloosa",
                            State = "Florida"
                        },
                        new
                        {
                            Id = -6,
                            City = "Hephzibah",
                            County = "Richmond",
                            State = "Georgia"
                        },
                        new
                        {
                            Id = -7,
                            City = "Augusta",
                            County = "Richmond",
                            State = "Georgia"
                        },
                        new
                        {
                            Id = -8,
                            City = "Fort Gordon",
                            County = "Richmond",
                            State = "Georgia"
                        },
                        new
                        {
                            Id = -9,
                            City = "Blythe",
                            County = "Richmond",
                            State = "Georgia"
                        });
                });

            modelBuilder.Entity("MSSA_Covid.Data.Models.PageStatistic", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("Hits")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Url")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("PageStatistics");
                });
#pragma warning restore 612, 618
        }
    }
}
